project:
  type: website
  output-dir: docs

website:
  title: "Wesley Neves"
  navbar:
    left:
      - href: index.qmd
        text: In√≠cio
      - href: research.qmd
        text: Pesquisa
      - href: teaching.qmd
        text: Ensino
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contato

format:
  html:
    theme: none
    css: styles.css
    cache: false
    toc: true