project:
  type: website
  output-dir: docs

website:
  title: "Wesley Neves"
  navbar:
    left:
      - href: index.qmd
        text: In√≠cio
      - href: pesquisa.qmd
        text: Pesquisa
      - href: ensino.qmd
        text: Ensino
      - href: cv.qmd
        text: CV
      - href: contato.qmd
        text: Contato
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false