project:
  type: website
  output-dir: docs

website:
  title: "Wesley Neves"
  description: "OceanÃ³grafo | Ecologia Marinha | Data Science"
  
  navbar:
    background: white
    search: true
    left:
      - href: about.qmd
        text: Sobre
      - href: curso.qmd
        text: "ðŸŽ“ Curso Sympla"
      - href: posts/index.qmd
        text: Blog/Dicas

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    lang: pt

render:
  - "*.qmd"
  - "posts/*.qmd"