project:
  type: website
  output-dir: docs

website:
  title: "Wesley Neves"
  description: "OceanÃ³grafo | Ecologia Marinha | Data Science"
  # Favicon opcional (se tiver um Ã­cone na pasta raiz)
  # favicon: logo.png 
  
  navbar:
    background: white
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Sobre
      - href: curso.qmd
        text: "ðŸŽ“ Curso Sympla" # Adicionei um emoji para destacar
      - href: posts/index.qmd  
        text: Blog/Dicas

format:
  html:
    theme: none # Mantendo seu CSS puro
    css: styles.css
    cache: false
    toc: true
    toc-title: "Nesta pÃ¡gina"
    lang: pt # Define o idioma do site para portuguÃªs

# Garante que o Quarto processe os arquivos dentro da pasta posts
render:
  - "*.qmd"
  - "posts/*.qmd"